dac, src/bin/generic_trait_objects.rs, src/bin/serde_enum.rs, src/domain/services/loader.rs, src/infra/config/mod.rs, src/infra/config/role.rs, src/injector.rs, src/main.rs
=> Added roles templates

disma-cli/src/infra/config/category.rs, disma-cli/src/infra/config/guild.rs, disma-cli/src/infra/config/role.rs, disma-cli/src/infra/diff/event.rs, disma-core/src/application/changes.rs, disma-core/src/domain/diff/event.rs, disma-core/src/utils/vec.rs
=> feat: small improvements

.github/workflows/build.yml, disma-cli/examples/base.yaml, disma-cli/examples/handlebars-template.yaml.hbs
Replace `mentionable` by `is_mentionable` in the examples for the CLI.
Nice work by the way 👍
=> Fix is_mentionable in the examples

codecov.yml, disma-cli/src/infra/config/channel/awaiting.rs, disma/src/application/changes.rs, disma/src/domain/channel/awaiting.rs, disma/src/domain/channel/commands.rs
=> Fix: Keep extra channels in categories

disma-cli/src/infra/diff/formatter.rs, disma/src/application/changes.rs, disma/src/domain/category/diff.rs, disma/src/domain/channel/diff.rs, disma/src/domain/permission/diff.rs, disma/src/domain/role/diff.rs, disma/src/infra/discord/api.rs, disma/src/utils/http.rs, disma/src/utils/option.rs, scripts/lint.sh
=> refactor: Replaced unwraps with Results for discord api implementation

disma/src/domain/permission/base.rs
- `VIEW_CREATOR_MONETIZATION_ANALYTICS` : `0x0000020000000000 (1 << 41)`
- `USE_SOUNDBOARD` : `0x0000040000000000 (1 << 42)`
- `USE_EXTERNAL_SOUNDS` : `0x0000200000000000 (1 << 45)`
- `SEND_VOICE_MESSAGES` : `0x0000400000000000 (1 << 46)`
=> feat: Added new permissions

disma/src/api/apply_changes.rs, disma/src/api/list_changes.rs, disma/src/application/params/category/existing.rs, disma/src/application/params/channel/awaiting.rs, disma/src/application/params/guild.rs, disma/src/core/changes/category.rs, disma/src/core/changes/mod.rs, disma/src/core/changes/role.rs, disma/src/domain/category/base.rs, disma/src/domain/role/base.rs, disma/src/test/fixtures/existing/category.rs, disma/src/test/fixtures/existing/guild.rs, disma/src/test/fixtures/existing/mod.rs, disma/src/test/fixtures/params/category.rs, disma/src/test/fixtures/params/guild.rs, disma/src/test/fixtures/params/mod.rs
=> refactor: new list changes usecase for categories

disma/src/api/apply_changes.rs
=> refactor: implemented  new apply changes usecase for categories

disma/src/api/list_changes.rs, disma/src/application/params/channel/existing.rs, disma/src/application/params/guild.rs, disma/src/core/changes/channel.rs, disma/src/core/changes/mod.rs, disma/src/domain/channel/base.rs, disma/src/test/fixtures/existing/channel.rs, disma/src/test/fixtures/existing/guild.rs, disma/src/test/fixtures/existing/mod.rs, disma/src/test/fixtures/params/channel.rs, disma/src/test/fixtures/params/guild.rs, disma/src/test/fixtures/params/mod.rs
=> refactor: new list changes usecase for channels

disma/src/api/apply_changes.rs, disma/src/api/list_changes.rs, disma/src/test/fixtures/existing/channel.rs, disma/src/test/mod.rs, disma/src/test/utils/mod.rs, disma/src/test/utils/vec.rs
=> refactor: implemented new apply changes usecase for channels

disma/src/api/apply_changes.rs, disma/src/core/commands/channel.rs, disma/src/core/commands/mod.rs, disma/src/core/commands/role.rs, disma/src/domain/role/commands.rs, disma/src/tests/fixtures/awaiting/mod.rs, disma/src/tests/fixtures/awaiting/role.rs, disma/src/tests/fixtures/commands/mod.rs, disma/src/tests/fixtures/commands/role.rs
=> refactor: added new role commands

disma-cli/src/infra/diff/event.rs, disma-cli/src/injector.rs, disma/src/api/apply_changes.rs, disma/src/core/commands/category.rs, disma/src/core/commands/mod.rs, disma/src/domain/category/commands.rs, disma/src/domain/commands.rs, disma/src/tests/fixtures/awaiting/category.rs, disma/src/tests/fixtures/awaiting/mod.rs, disma/src/tests/fixtures/awaiting/role.rs, disma/src/tests/fixtures/commands/category.rs, disma/src/tests/fixtures/commands/mod.rs
=> Refactor: New category commands

disma/src/api/apply_changes.rs, disma/src/domain/category/extra.rs, disma/src/domain/category/mod.rs, disma/src/domain/channel/extra.rs, disma/src/domain/channel/mod.rs, disma/src/domain/commands.rs, disma/src/domain/role/extra.rs, disma/src/domain/role/mod.rs, scripts/lint.sh
=> refactor: Using new commands for extra items

disma-cli/src/services/list_guilds.rs, disma/src/domain/guild.rs, disma/src/impls/discord/api.rs, disma/src/impls/discord/dtos/guild.rs
=> feat: Added members count when listing guilds

Cargo.lock, disma-cli/Cargo.toml, disma-cli/src/services/list_guilds.rs, disma/src/domain/guild.rs, disma/src/domain/permission/base.rs, disma/src/impls/discord/dtos/guild.rs
=> feat: added permissions check when listing guilds

disma/src/api/params/category/awaiting.rs, disma/src/api/params/category/existing.rs, disma/src/api/params/channel/awaiting.rs, disma/src/api/params/channel/existing.rs, disma/src/api/params/guild.rs, disma/src/api/params/permission.rs, disma/src/core/diffs/category.rs, disma/src/core/diffs/channel.rs, disma/src/core/diffs/permission.rs, disma/src/domain/category/awaiting.rs, disma/src/domain/category/existing.rs, disma/src/domain/channel/awaiting.rs, disma/src/domain/channel/existing.rs, disma/src/domain/permission/base.rs, disma/src/domain/permission/overwrites.rs, disma/src/impls/discord/dtos/permissions.rs, disma/src/impls/discord/http_querier.rs, disma/src/tests/fixtures/awaiting/category.rs, disma/src/tests/fixtures/awaiting/channel.rs, disma/src/tests/fixtures/existing/category.rs, disma/src/tests/fixtures/existing/channel.rs
=> refactor: removed full entities from permissions overwrites

disma/src/api/params/channel/existing.rs, disma/src/core/diffs/channel.rs, disma/src/domain/channel/existing.rs, disma/src/impls/discord/http_querier.rs, disma/src/tests/fixtures/existing/channel.rs
=> refactor: simplified existing channel category reference

disma/src/api/apply_changes.rs, disma/src/core/commands/role.rs, disma/src/domain/guild/command.rs, disma/src/impls/discord/http_commander.rs
=> refactor: returning existing roles on roles commander actions

disma/src/api/apply_changes.rs, disma/src/core/commands/category.rs, disma/src/domain/guild/command.rs, disma/src/impls/discord/dtos/channel.rs, disma/src/impls/discord/dtos/permissions.rs, disma/src/impls/discord/http_commander.rs, disma/src/impls/discord/http_querier.rs
=> refactor: returning category entities for commander actions

disma/src/api/apply_changes.rs, disma/src/core/commands/channel.rs, disma/src/domain/channel/existing.rs, disma/src/domain/guild/command.rs, disma/src/impls/discord/dtos/channel.rs, disma/src/impls/discord/dtos/permissions.rs, disma/src/impls/discord/http_commander.rs, disma/src/impls/discord/http_querier.rs
=> refactor: returning existing entities on channel commander actions

disma/src/api/apply_changes.rs, disma/src/api/params/guild.rs, disma/src/core/changes/role.rs, disma/src/domain/guild/query.rs, disma/src/domain/role/base.rs, disma/src/impls/discord/http_querier.rs, disma/src/tests/fixtures/existing/guild.rs
=> refactor: allow updating existing roles

disma/src/api/apply_changes.rs, disma/src/api/params/guild.rs, disma/src/core/changes/category.rs, disma/src/core/changes/channel.rs, disma/src/domain/category/base.rs, disma/src/domain/channel/base.rs, disma/src/domain/guild/query.rs, disma/src/tests/fixtures/existing/guild.rs
=> feat: update existing channels and categories

disma/src/api/params/channel/existing.rs, disma/src/core/diffs/channel.rs, disma/src/domain/channel/existing.rs, disma/src/impls/discord/dtos/channel.rs, disma/src/tests/fixtures/existing/channel.rs
This reverts commit 379c1b1248461ac1ab733e0482799a089097b844.
=> Revert "refactor: simplified existing channel category reference (#111)"

Cargo.lock, disma/Cargo.toml, disma/src/domain/category/base.rs, disma/src/domain/category/existing.rs, disma/src/domain/channel/base.rs, disma/src/domain/channel/list.rs, disma/src/domain/channel/mod.rs, disma/src/domain/role/base.rs, disma/src/domain/role/existing.rs, disma/src/impls/discord/dtos/channel.rs, disma/src/tests/fixtures/existing/category.rs, disma/src/tests/fixtures/existing/channel.rs, disma/src/tests/fixtures/existing/role.rs
=> test: list tests

disma/src/core/commands/category.rs, disma/src/core/commands/channel.rs, disma/src/core/commands/role.rs, disma/src/tests/fixtures/awaiting/role.rs, disma/src/tests/fixtures/commands/role.rs
=> test: guild updates

disma/src/api/apply_changes.rs, disma/src/core/changes/category.rs, disma/src/core/changes/channel.rs, disma/src/core/changes/role.rs, disma/src/domain/category/extra.rs, disma/src/domain/channel/extra.rs, disma/src/domain/role/extra.rs, disma/src/tests/fixtures/awaiting/channel.rs, disma/src/tests/fixtures/existing/category.rs, disma/src/tests/fixtures/existing/channel.rs
=> test: extra items strategy

disma/src/api/params/category/mod.rs, disma/src/api/params/channel/mod.rs, disma/src/api/params/role/mod.rs, disma/src/core/commands/category.rs, scripts/lint.sh
=> fix: using the right entity
